name: build hostapd-hwsim-runner container

on:
  pull_request:
    paths:
      - .containers/hostapd-hwsim-runner/**
      - .github/workflows/build-hostapd-hwsim-runner.yaml
  push:
    paths:
      - .containers/hostapd-hwsim-runner/**
      - .github/workflows/build-hostapd-hwsim-runner.yaml
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: project-chip/hostapd-hwsim-runner
          context: .containers/hostapd-hwsim-runner
          registry: ghcr.io
          tags: "latest,${{ github.sha }}"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          no_push: ${{ github.repository_owner != 'project-chip' || github.event_name == 'pull_request' || github.event.ref != 'refs/heads/main' }}
