name: build matter packages

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run only the build step in the container rather than the whole job, because the UID of the
      # buildbot user (1000) that owns the OpenWrt SDK files in /builder doesn't match the UID of
      # the GitHub runner user (1001), causing file system permission issues.
      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/project-chip/matter-openwrt-build:23.05.4
          options: --volume ${{ github.workspace }}:/workspace
          shell: bash
          run: |
            set -x
            wget -qO - https://github.com/openwrt/openwrt/pull/13000.patch | patch -p1
            echo "src-link --force matter /workspace" >>feeds.conf
            ./scripts/feeds update matter
            ./scripts/feeds install -a -p matter
            cat feeds/matter/.config.ci >.config
            make defconfig
            failed=()
            for pkg in $(awk -F '[[:space:]]|/' '/^Source-Makefile:/{print$(NF-1)}' feeds/matter.index); do
              echo "::group::Building $pkg"
              if ! make -j "$(nproc)" "package/$pkg/compile"; then
                failed+=("$pkg")
                make "package/$pkg/compile" V=s || true # re-run with verbose output
              fi
              echo "::endgroup::"
            done
            if [[ "${#failed[@]}" -gt 0 ]]; then
              echo "ERROR: Some packages failed to build: ${failed[*]}"
              exit 2
            fi
